---
title: "Basis functions, alternative illustrations"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: false
    fig_caption: true
    code_download: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---


```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
.caption {
  margin: auto;
  text-align: center;
  margin-bottom: 20px; /* Spacing below the box */
}
```


Go back to the [About page](about.html).

Go back to the [Basis Functions](basis_functions.html) page.

Let us set some global options for all code chunks in this document.


```{r}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```

# Import libraries

```{r}
library(MetricGraph)
library(dplyr)
library(plotly)

library(here)
library(rmarkdown)
library(grateful) # to cite
```

# By hand

<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>

```{r,  fig.height = 8, out.width = "100%", class.source = "fold-hide"}
gets.graph.tadpole <- function(h){
  edge1 <- rbind(c(0,0),c(1,0))
  theta <- seq(from=-pi,to=pi,length.out = 100)
  edge2 <- cbind(1+1/pi+cos(theta)/pi,sin(theta)/pi)
  edges <- list(edge1, edge2)
  graph <- metric_graph$new(edges = edges)
  graph$set_manual_edge_lengths(edge_lengths = c(1,2))
  graph$build_mesh(h = h)
  return(graph)
}

graph <- gets.graph.tadpole(h = 1/4)

graph_to_get_loc <- gets.graph.tadpole(h = 1/40)

loc <- graph_to_get_loc$get_mesh_locations()
```

```
{r}
A <- graph$fem_basis(loc)
p <- NULL  # initialize the plotly object
graph_to_get_loc$plot_function(X = A[, 2], p = p, vertex_size = 0, type = "plotly")
```



```
{r,  fig.height = 8, out.width = "100%", class.source = "fold-hide"}
A <- graph$fem_basis(loc)
p <- NULL  # initialize the plotly object

for (i in 1:ncol(A)) {
  p <- graph_to_get_loc$plot_function(X = A[, i], p = p, vertex_size = 0, type = "plotly")
}

x <- graph$mesh$V[, 1]
y <- graph$mesh$V[, 2]
x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)
p %>% 
  layout(
    scene = list(
      xaxis = list(title = "x", range = y_range),
      yaxis = list(title = "y", range = x_range),
      zaxis = list(title = "z", range = z_range),
      aspectratio = list(x = 1.2, y = 2.4, z = 0.3),
      camera = list(eye = list(x = -1.5, y = 1.5, z = 1), center = list(x = 0, y = 0, z = 0))))

```


```
{r}
plotting.order <- function(v, graph){
  edge_number <- graph$mesh$VtE[, 1]
  pos <- sum(edge_number == 1)+1
  return(c(v[1], v[3:pos], v[2], v[(pos+1):length(v)], v[2]))
}

A <- graph$fem_basis(loc)
A <- cbind(A, A[, 1]*0) # add the first column to the end to close the loop
x <- graph_to_get_loc$mesh$V[, 1]
y <- graph_to_get_loc$mesh$V[, 2]
x <- plotting.order(x, graph_to_get_loc)
y <- plotting.order(y, graph_to_get_loc)
x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)

# Initialize plotly object
p <- plot_ly()

# Add a trace for each column in A
for (i in 1:ncol(A)) {
  if(i == ncol(A)) mycolor <- "black"
  else mycolor <- "blue"
  z <- plotting.order(A[, i], graph_to_get_loc)
  p <- add_trace(p, x = x, y = y, z = z, type = "scatter3d", mode = "lines", line = list(color = mycolor, width = 2))
}

# Show the final plot
p

```


```{r, fig.dim = c(12,12)}
library(plotly)

plotting.order <- function(v, graph){
  edge_number <- graph$mesh$VtE[, 1]
  pos <- sum(edge_number == 1) + 1
  return(c(v[1], v[3:pos], v[2], v[(pos+1):length(v)], v[2]))
}

A <- graph$fem_basis(loc)
A <- cbind(A, A[, 1]*0)  # add the first column to the end to close the loop

x <- graph_to_get_loc$mesh$V[, 1]
y <- graph_to_get_loc$mesh$V[, 2]
x <- plotting.order(x, graph_to_get_loc)
y <- plotting.order(y, graph_to_get_loc)

x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)

# Start plot
p <- plot_ly()

# Add function lines
for (i in 1:ncol(A)) {
  z <- plotting.order(A[, i], graph_to_get_loc)
  mycolor <- if (i == ncol(A)) "black" else "blue"
  if (i==2) mycolor <- "red"
  # Add basis function trace
  p <- add_trace(p, x = x, y = y, z = z, type = "scatter3d", mode = "lines",
                 line = list(color = mycolor, width = 2), name = paste0("Basis ", i))
  
  # Add vertical segments from (x, y, 0) to (x, y, z)
  for (j in 1:length(x)) {
    p <- add_trace(p,
      x = rep(x[j], 2),
      y = rep(y[j], 2),
      z = c(0, z[j]),
      type = "scatter3d",
      mode = "lines",
      line = list(color = "gray", width = 1),
      showlegend = FALSE
    )
  }
}

# Display plot
p %>% layout(
    scene = list(
      xaxis = list(title = "x", range = x_range),
      yaxis = list(title = "y", range = y_range),
      zaxis = list(title = "z", range = z_range),
      aspectratio = list(x = 2.4, y = 1.2, z = 0.6),
      camera = list(eye = list(x = 3, y = 3, z = 4), center = list(x = 0, y = 0, z = 0))))

```


# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```

