---
title: "Basis functions, alternative illustrations"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: false
    fig_caption: true
    code_download: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---


```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
.caption {
  margin: auto;
  text-align: center;
  margin-bottom: 20px; /* Spacing below the box */
}
```


Go back to the [About page](about.html).

Go back to the [Basis Functions](basis_functions.html) page.

Let us set some global options for all code chunks in this document.


```{r}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```

# Import libraries

```{r}
library(MetricGraph)
library(dplyr)
library(plotly)

library(here)
library(rmarkdown)
library(grateful) # to cite
```

# By hand

<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>

```{r,  fig.height = 8, out.width = "100%", class.source = "fold-hide"}
gets.graph.tadpole <- function(h){
#F
edge1 <- rbind(c(0,0), c(0,2))
edge2 <- rbind(c(0,2), c(0,4))
edge3 <- rbind(c(0,2), c(1,2))
edge4 <- rbind(c(0,4), c(2,4))
#U
edge5 <- rbind(c(2,4), c(2,1))
thetau <- seq(pi, 2*pi, length.out = 100)
edge6 <- cbind(3+1*cos(thetau), 1+1*sin(thetau))
edge7 <- rbind(c(4,1), c(4,4))
#N
edge8 <- rbind(c(4,1), c(4,0))
edge9 <- rbind(c(4,4), c(6,0))
edge10 <- rbind(c(6,0), c(6,4))
#C
thetac1 <- seq(pi, pi/2, length.out = 100)
edge11 <- cbind(8+2*cos(thetac1), 2+2*sin(thetac1))
thetac2 <- seq(pi, 3*pi/2, length.out = 100)
edge12 <- cbind(8+2*cos(thetac2), 2+2*sin(thetac2))
#T
edge13 <- rbind(c(8,4), c(10,4))
edge14 <- rbind(c(9,4), c(9,0))
#I
edge15 <- rbind(c(10,4), c(12,4))
edge16 <- rbind(c(10,0), c(12,0))
edge17 <- rbind(c(11,0), c(11,4))
#O
thetao1 <- seq(pi, 2*pi, length.out = 100)
edge18 <- cbind(13+1*cos(thetao1), 1+1*sin(thetao1))
thetao2 <- seq(0, pi, length.out = 100)
edge19 <- cbind(13+1*cos(thetao2), 3+1*sin(thetao2))
edge20 <- rbind(c(12,3), c(12,1))
edge21 <- rbind(c(14,1), c(14,4))
#N
edge22 <- rbind(c(14,4), c(16,0))
edge23 <- rbind(c(16,0), c(16,4))
edge56 <- rbind(c(14,0), c(14,1))
#S
edge24 <- rbind(c(16,0), c(17,0))
tethas1 <- seq(-pi/2, pi/2, length.out = 100)
edge25 <- cbind(17+1*cos(tethas1), 1+1*sin(tethas1))
thetas2 <- seq(3*pi/2, pi/2, length.out = 100)
edge26 <- cbind(17+1*cos(thetas2), 3+1*sin(thetas2))
edge27 <- rbind(c(17,4), c(18,4))
#H
edge28 <- rbind(c(0,4), c(0,6))
edge29 <- rbind(c(0,6), c(0,8))
edge30 <- rbind(c(0,6), c(2,6))
edge31 <- rbind(c(2,4), c(2,8))
#A
edge32 <- rbind(c(2,4), c(3,8))
edge33 <- rbind(c(3,8), c(4,4))
edge34 <- rbind(c(2.5,6), c(3.5,6))
#T
edge35 <- rbind(c(3,8), c(6,8))
edge36 <- rbind(c(5,8), c(5,4))
#B
edge37 <- rbind(c(8,8), c(8,4))
thetab1 <- seq(-pi/2, pi/2, length.out = 100)
edge38 <- cbind(9+1*cos(thetab1), 5+1*sin(thetab1))
edge39 <- rbind(c(8,6), c(9,6))
edge40 <- rbind(c(9,8), c(8,8))
thetab2 <- seq(-pi/2, pi/2, length.out = 100)
edge41 <- cbind(9+1*cos(thetab2), 7+1*sin(thetab2))
#A
edge42 <- rbind(c(10,4), c(11,8))
edge43 <- rbind(c(11,8), c(12,4))
edge44 <- rbind(c(10.5,6), c(11.5,6))
#S

#I
edge45 <- rbind(c(14,4), c(16,4))
edge46 <- rbind(c(15,4), c(15,8))
edge47 <- rbind(c(14,8), c(16,8))
#S
edge48 <- rbind(c(16,4), c(17,4))
edge49 <- cbind(17+1*cos(tethas1), 5+1*sin(tethas1))
edge50 <- cbind(17+1*cos(thetas2), 7+1*sin(thetas2))
edge51 <- rbind(c(17,8), c(18,8))
#S
edge52 <- rbind(c(13,8), c(14,8))
edge53 <-cbind(13+1*cos(thetas2), 7+1*sin(thetas2))
edge54 <- cbind(13+1*cos(tethas1), 5+1*sin(tethas1))
edge55 <- rbind(c(12,4), c(13,4))

edges <- list(edge1, edge2, edge3, edge4, edge5, edge6, edge7,
              edge8, edge9, edge10, edge11, edge12, edge13, edge14,
              edge15, edge16, edge17, edge18, edge19, edge20, edge21,
              edge22, edge23, edge24, edge25, edge26, edge27,
              edge28, edge29, edge30, edge31, edge32, edge33, edge34,
              edge35, edge36, edge37, edge38, edge39, edge40, edge41,
              edge42, edge43, edge44, edge45, edge46, edge47,
              edge48, edge49, edge50, edge51, edge52, edge53, edge54, edge55, edge56)
graph <- metric_graph$new(edges = edges, perform_merges = TRUE)
graph$prune_vertices()
  graph$build_mesh(h = h)
  return(graph)
}

graph <- gets.graph.tadpole(h = 1/2)

graph_to_get_loc <- gets.graph.tadpole(h = 1/10)

loc <- graph_to_get_loc$get_mesh_locations()
```

```{r, fig.dim = c(12,12)}
x <- graph_to_get_loc$mesh$V[, 1]
y <- graph_to_get_loc$mesh$V[, 2]

x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)
A <- graph$fem_basis(loc)
A <- cbind(A, A[, 1]*0)  # add the first column to the end to close the loop

p <- NULL  # initialize the plotly object
for (i in 1:ncol(A)) {
  if (i%in% 1:graph$nV) {
    mycolor <- "red"
  } else {
    mycolor <- "blue"
  }
  if (i==ncol(A)) {
    mycolor <- "black"
  } 
  p <- graph_to_get_loc$plot_function(X = A[, i], p = p, vertex_size = 0, type = "plotly", line_color = mycolor, line_width = 2)
}
p %>% layout(
    scene = list(
      xaxis = list(title = "x", range = y_range),
      yaxis = list(title = "y", range = x_range),
      zaxis = list(title = "z", range = z_range),
      aspectratio = list(x = 1.2, y = 2.4, z = 0.1),
      camera = list(eye = list(x = 3, y = -3, z = 4), center = list(x = 0, y = 0, z = 0))))

```

```
{r, fig.dim = c(12,12)}
A <- graph$fem_basis(loc)
p <- NULL  # initialize the plotly object

for (i in 1:ncol(A)) {
  p <- graph_to_get_loc$plot_function(X = A[, i], p = p, vertex_size = 0, type = "plotly")
}

x <- graph$mesh$V[, 1]
y <- graph$mesh$V[, 2]
x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)
p %>% 
  layout(
    scene = list(
      xaxis = list(title = "x", range = y_range),
      yaxis = list(title = "y", range = x_range),
      zaxis = list(title = "z", range = z_range),
      aspectratio = list(x = 1.2, y = 2.4, z = 0.3),
      camera = list(eye = list(x = -1.5, y = 1.5, z = 1), center = list(x = 0, y = 0, z = 0))))

```


```
{r, fig.dim = c(12,12)}
library(plotly)

plotting.order <- function(v, graph){
  edge_number <- graph$mesh$VtE[, 1]
  pos <- sum(edge_number == 1) + 1
  return(c(v[1], v[3:pos], v[2], v[(pos+1):length(v)], v[2]))
}

A <- graph$fem_basis(loc)
A <- cbind(A, A[, 1]*0)  # add the first column to the end to close the loop

x <- graph_to_get_loc$mesh$V[, 1]
y <- graph_to_get_loc$mesh$V[, 2]
# x <- plotting.order(x, graph_to_get_loc)
# y <- plotting.order(y, graph_to_get_loc)

x_range <- range(x)
y_range <- range(y)
z_range <- c(0,1)

# Start plot
p <- plot_ly()

# Add function lines
for (i in 1:ncol(A)) {
  #z <- plotting.order(A[, i], graph_to_get_loc)
  z <- A[, i]
  if (i%in% 1:graph$nV) {
    mycolor <- "red"
  } else {
    mycolor <- "blue"
  }
  if (i==ncol(A)) {
    mycolor <- "black"
  } 
  # Add basis function trace
  p <- add_trace(p, x = x, y = y, z = z, type = "scatter3d", mode = "markers",
                 marker = list(size = 1, color = mycolor, opacity = 0.8),
                 name = paste("Basis function", i), showlegend = FALSE)
  
  # # Add vertical segments from (x, y, 0) to (x, y, z)
  # for (j in 1:length(x)) {
  #   p <- add_trace(p,
  #     x = rep(x[j], 2),
  #     y = rep(y[j], 2),
  #     z = c(0, z[j]),
  #     type = "scatter3d",
  #     mode = "lines",
  #     line = list(color = "gray", width = 1),
  #     showlegend = FALSE
  #   )
  # }
}

# Display plot
p %>% layout(
    scene = list(
      xaxis = list(title = "x", range = x_range),
      yaxis = list(title = "y", range = y_range),
      zaxis = list(title = "z", range = z_range),
      aspectratio = list(x = 2.4, y = 1.2, z = 0.1),
      camera = list(eye = list(x = -3, y = -3, z = 4), center = list(x = 0, y = 0, z = 0))))

```


# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```

